name: 'Netflex Service Helper'
description: Helps Netflex users control services through github actions
inputs:
  pull_request:
    description: "Pull request number"
    required: true
  base_revision:
    description: The revision of the action that we want to use as a base to create a new revision
    required: true
    default: "1"
  site_name:
    description: Site alias. Should be "netflexapp" or url friendly site alias of site.
    required: true
  repository_url:
    description: Part of the Docker repository url. Has to be in a format for example "apility/netflexapp" or "netflexsites/grieghallen"
    required: true
  mode:
    description: Either -m or -t for (make or teardown) Make will create/update service, teardown will only delete service
    required: true
    default: -m
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--pull-request="${{ inputs.pull_request }}" --revision="${{ inputs.base_revision}}"'